export const GET_USER_BLKCHECK = 'GET_USER_BLKCHECK';
export const SET_USER_BLKCHECK = 'SET_USER_BLKCHECK';

export const GET_ACC_BLKCHECK = 'GET_ACC_BLKCHECK';
export const SET_ACC_BLKCHECK = 'SET_ACC_BLKCHECK';
